spring:
  application:
    name: ${APP_NAME:retail-poc}

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}
      platform: ${SPRING_SQL_PLATFORM:postgres}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:retail_poc}
    username: ${DB_USERNAME:retail_user}
    password: ${DB_PASSWORD:retail_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${HIBERNATE_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

server:
  port: ${SERVER_PORT:8080}
