apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-frontend
  namespace: retail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-frontend
  template:
    metadata:
      labels:
        app: retail-frontend
    spec:
      containers:
      - name: retail-frontend
        image: ssurajparfr/retail-frontend:e2660c1a30e6c09a5b37bedc21f6f20153410a37
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://my.retail.local/api"
