apiVersion: v1
kind: Service
metadata:
  name: retail-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: retail-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
